spring:
  datasource:
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    ##driver-class-name: com.github.housepower.jdbc.ClickHouseDriver
    url: jdbc:clickhouse://127.0.0.1:8123/user_info?characterEncoding=UTF-8&useSSL=false
  application:
    name: bigdata
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  ## 实体类包名称
  type-aliases-package: com.nivelle.bigdata.clickhouse.Entity
  mapper-locations: classpath:mapper/*.xml